// Mocks generated by Mockito 5.4.4 from annotations
// in three_sixty_evaluations/test/screens/see_feedback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:three_sixty_evaluations/screens/network/models/personal_feedback_item.dart'
    as _i2;
import 'package:three_sixty_evaluations/screens/network/repositories/personal_feedback_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePersonalFeedback_0 extends _i1.SmartFake
    implements _i2.PersonalFeedback {
  _FakePersonalFeedback_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonalFeedbackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalFeedbackRepository extends _i1.Mock
    implements _i3.PersonalFeedbackRepository {
  @override
  _i2.PersonalFeedback fetchPersonalFeedback() => (super.noSuchMethod(
        Invocation.method(
          #fetchPersonalFeedback,
          [],
        ),
        returnValue: _FakePersonalFeedback_0(
          this,
          Invocation.method(
            #fetchPersonalFeedback,
            [],
          ),
        ),
        returnValueForMissingStub: _FakePersonalFeedback_0(
          this,
          Invocation.method(
            #fetchPersonalFeedback,
            [],
          ),
        ),
      ) as _i2.PersonalFeedback);
}
